### ISSUE TITLE
[fix] 벌크성 update 로직 query dsl로 마이그레이션

### ISSUE THREAD

**Issue by KWY0218** [ASAP-as-soon-as-possible/ASAP_Server#240]
## 📌  Feature Issue

벌크성 update 로직 query dsl로 마이그레이션

## 📝  To-do

- [ ] querydsl 디펜던시 추가
- [ ] user repository custom 생성
- [ ] query dsl 쿼리 작성
- [ ] 적용
